config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'prices/index'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/contact',    to: 'static_pages#contact'
  get  '/news',    to: 'articles#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :articles
  resources :users
  resources :prices
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :orders,          only: [:new, :show, :create, :destroy] do
    resource :goods_in_orders, only: [:create]
  end
  resource :boxes
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :goods_in_orders, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  accepts_nested_attributes_for :goods_in_orders
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: :destroy

  def new
    @order = current_user.orders.build #???????
   # @goods_in_order = @order.goods_in_orders.build
   # @user = current_user
  end

  def create
    @order = current_user.orders.build(order_params)
    #@goods_in_order.order_id = @order.id
    if @order.save
      #flash[:success] = "Order created!"
      redirect_to new_boxes_path
    else
      render 'static_pages/home'
    end
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def destroy
    @order.destroy
    flash[:success] = "Order deleted"
    redirect_to request.referrer || root_url
  end

  private

  def order_params
    params.require(:order).permit(:address, :payment_method, :delivery_method,
                                  :comment) #, goods_in_orders_attributes: [:order_id, :box_count, :box_id])
  end

  def correct_user
    @order = current_user.orders.find_by(id: params[:id])
    redirect_to root_url if @order.nil?
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/views/orders/_order.html.erb
<div class="order">
  <li>
    <div class="avatar">
      <%= image_tag image_path("box.png") %>
    </div>
    <div class="col">
      <span class="user_name"><%= link_to order.user.name, order.user %></span>
    </div>
    <div class="col">
    <span class="order_heading">Заказ №<%= order.id %></span>
    </div>
    <div class="col">
      <%= order.created_at.strftime("%d.%m.%Y") %>
    </div>
    <div class="col">
      <%= link_to "Показать", order_path%>
    </div>
    <div class="col">
        <%= link_to "Удалить", order, method: :delete, data: { confirm: "Вы уверены?" } %>
    </div>

    <div class="col">
      <span id="button_type1">В обработке</span>
    </div>
  </li>
</div>

app/views/orders/new.html.erb
<% provide(:title, "Новый заказ") %>
  <div class="row" style="padding-top: 150px">
    <aside class="col-md-4">
      <section class="user_info">
        <%#= render 'shared/user_info' %>
      </section>
      <section class="order_form">
        <%= render 'shared/order_form' %>
      </section>
    </aside>
  </div>

app/views/orders/show.html.erb
<div class="content" style="padding-top: 150px">
  <span class="content"><%= @order.address %></span>
  <span class="content"><%= @order.created_at %></span>
  <span class="content"><%#= @order.goods_in_orders.box %></span>
</div>